Repository apache/maven-archiver, pull requests merged in 2025-09, with the labels that each got.

#302 Cleanup dependencies
  .github/workflows/maven-verify.yml
  pom.xml
Labels: dependencies

#311 don't limit outputTimestamp to zip (MS DOS) range
  src/main/java/org/apache/maven/archiver/MavenArchiver.java
  src/test/java/org/apache/maven/archiver/MavenArchiverTest.java
Labels: bug

#315 document Java-Version entry added in #299
  src/site/xdoc/index.xml.vm
Labels: documentation
