Repository apache/maven-archiver, pull requests merged in 2025-08, with the labels that each got.

#282 Upgrade to maven-4.0.0-rc-4 and maven-plugin-testing-harness-4.0.0-beta-4
  pom.xml
Labels: dependencies

#291 Add tag-template to release-drafter configuration
  .github/release-drafter-3.x.yml
  .github/release-drafter.yml
Labels: maintenance

#292 Update site descriptor to 2.0.0
  src/site/site.xml
Labels: maintenance

#290 some javadoc nits
  src/main/java/org/apache/maven/shared/archiver/ManifestConfiguration.java
  src/main/java/org/apache/maven/shared/archiver/ManifestSection.java
  src/main/java/org/apache/maven/shared/archiver/MavenArchiveConfiguration.java
Labels: documentation

#301 feat: enable prevent branch protection rules
  .asf.yaml
Labels: maintenance

#299 [MSHARED-1466] add Java-Version entry to default MANIFEST.MF
  pom.xml
  src/main/java/org/apache/maven/shared/archiver/BuildHelper.java
  src/main/java/org/apache/maven/shared/archiver/MavenArchiver.java
Labels: enhancement
